/**
 * Core types for Ashes of the Ever Sun
 * Copyright (C) 2026 Rogel S.J. Corral
 */

export type Alignment = 'Spark' | 'Embers' | 'Ash';

export interface PlayerStats {
  health: number;      // Physical well-being (0-20)
  sanity: number;      // Resistance to the "Hollow" influence
  light: number;       // Current fuel/radiance level for survival
  willpower: number;   // Modifier for mental checks
}

export interface InventoryItem {
  id: string;
  name: string;
  description: string;
  quantity: number;
  type: 'resource' | 'tool' | 'relic';
}

export interface GameState {
  player: PlayerStats;
  inventory: InventoryItem[];
  location: string;
  alignment: Alignment;
  dayCount: number;
  isGameOver: boolean;
}

export interface NarrativeNode {
  id: string;
  text: string;         // The prose generated by Gemini
  choices: Choice[];    // Options presented to the player
  timestamp: number;
}

export interface Choice {
  label: string;        // e.g., "Investigate the Altar"
  action: string;       // The instruction sent back to the engine
  difficulty?: number;  // The DC (Difficulty Class) for a d20 roll
}
